version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - './.postgres-data/db:/var/lib/postgresql/data'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres